[theme]
primaryColor="#BEDAFA"
secondaryBackgroundColor="#F8F7F2"
textColor="#384B60"
font="Pretendard JP Variable"


#primaryColor="#0C508B"
#secondaryBackgroundColor="#F0F4F3"
#textColor="#0C508B"
#font="Pretendard JP Variable"


#살구색+검붉은색
#primaryColor="#C0504D"
#secondaryBackgroundColor="#FCF9F6"
#textColor="#000000"
#font="Pretendard JP Variable"

#연두+진노랑
#[theme]
#primaryColor="#f1cb41"
#secondaryBackgroundColor="#f2f7ef"
#textColor="#000000"



#[theme]
#base="light"
#primaryColor="#4b4bcb"
#secondaryBackgroundColor="#dae4f7"
